import {
  LayoutDashboard,
  ScanSearch,
  Tag,
  Store,
  Truck,
  ClipboardList,
  Award,
  Leaf,
  BookOpen,
  TriangleAlert,
  Bell,
  User,
  Users,
  Trash2,
  UserCog,
  Handshake,
  Layers,
  Gift,
  ChartColumn,
  Settings,
  CircleCheck,
  Building2,
} from 'lucide-react';

export const NAV_ITEMS = {
  user: [
    { to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/identify', label: 'Identify Waste', icon: ScanSearch },
    { to: '/sell', label: 'Sell Waste', icon: Tag },
    { to: '/marketplace', label: 'Marketplace', icon: Store },
    { to: '/pickups/new', label: 'Request Pickup', icon: Truck },
    { to: '/pickups', label: 'My Pickups', icon: ClipboardList, end: true },
    { to: '/eco-points', label: 'EcoPoints', icon: Award },
    { to: '/impact', label: 'Environmental Impact', icon: Leaf },
    { to: '/guide', label: 'Disposal Guide', icon: BookOpen },
    { to: '/report', label: 'Report Problem', icon: TriangleAlert },
    { to: '/partners', label: 'Recycling Partners', icon: Building2 },
    { to: '/notifications', label: 'Notifications', icon: Bell },
    { to: '/profile', label: 'Profile', icon: User },
  ],
  collector: [
    { to: '/collector', label: 'Dashboard', icon: LayoutDashboard, end: true },
    { to: '/collector/assigned', label: 'Assigned Pickups', icon: Truck },
    { to: '/collector/completed', label: 'Completed Pickups', icon: CircleCheck },
    { to: '/marketplace', label: 'Marketplace', icon: Store },
    { to: '/guide', label: 'Disposal Guide', icon: BookOpen },
    { to: '/notifications', label: 'Notifications', icon: Bell },
    { to: '/profile', label: 'Profile', icon: User },
  ],
  admin: [
    { to: '/admin', label: 'Dashboard', icon: LayoutDashboard, end: true },
    { to: '/admin/users', label: 'Users', icon: Users },
    { to: '/admin/waste', label: 'Waste', icon: Trash2 },
    { to: '/admin/marketplace', label: 'Marketplace', icon: Store },
    { to: '/admin/pickups', label: 'Pickups', icon: Truck },
    { to: '/admin/collectors', label: 'Collectors', icon: UserCog },
    { to: '/admin/complaints', label: 'Complaints', icon: TriangleAlert },
    { to: '/admin/partners', label: 'Partners', icon: Handshake },
    { to: '/admin/categories', label: 'Categories', icon: Layers },
    { to: '/admin/rewards', label: 'Rewards', icon: Gift },
    { to: '/admin/analytics', label: 'Analytics', icon: ChartColumn },
    { to: '/admin/settings', label: 'Settings', icon: Settings },
    { to: '/notifications', label: 'Notifications', icon: Bell },
    { to: '/profile', label: 'Profile', icon: User },
  ],
};
