// Static disposal guide - works without AI or internet access to Firestore.
export const GUIDE_ITEMS = [
  {
    name: 'Plastic bottle',
    keywords: 'pet bottle water bottle soft drink plastic',
    category: 'recyclable',
    action: 'Empty, rinse and flatten. Place in recyclable waste or submit it for recycling.',
    canRecycle: true,
    canSell: true,
    pickup: true,
    safety: 'Remove caps and labels if your local recycler asks for it.',
  },
  {
    name: 'Paper',
    keywords: 'newspaper office paper notebook magazine',
    category: 'recyclable',
    action: 'Keep dry and bundle together. Sell to a scrap dealer or recycle.',
    canRecycle: true,
    canSell: true,
    pickup: true,
    safety: 'Oily or wet paper (e.g. food-stained) should go to general waste.',
  },
  {
    name: 'Cardboard',
    keywords: 'carton box packaging corrugated',
    category: 'recyclable',
    action: 'Flatten boxes, keep dry and recycle or sell.',
    canRecycle: true,
    canSell: true,
    pickup: true,
    safety: 'Remove tape and plastic wrapping where possible.',
  },
  {
    name: 'Glass',
    keywords: 'glass bottle jar',
    category: 'recyclable',
    action: 'Rinse and place in recyclable waste. Keep separate from other recyclables.',
    canRecycle: true,
    canSell: true,
    pickup: true,
    safety: 'Wrap broken glass in newspaper and label it to protect waste handlers.',
  },
  {
    name: 'Metal',
    keywords: 'aluminium can tin steel iron copper scrap',
    category: 'recyclable',
    action: 'Rinse cans and collect scrap metal separately. Metal has good resale value.',
    canRecycle: true,
    canSell: true,
    pickup: true,
    safety: 'Handle sharp edges carefully. Never put aerosol cans in fire.',
  },
  {
    name: 'Food waste',
    keywords: 'leftover food kitchen waste vegetable peel fruit',
    category: 'organic',
    action: 'Consider home composting or organic-waste collection.',
    canRecycle: false,
    canSell: false,
    pickup: true,
    safety: 'Keep in a covered bin to avoid pests and odour.',
  },
  {
    name: 'Garden waste',
    keywords: 'leaves grass branches flowers',
    category: 'organic',
    action: 'Compost at home or hand over for organic-waste collection.',
    canRecycle: false,
    canSell: false,
    pickup: true,
    safety: 'Do not burn garden waste - it causes air pollution.',
  },
  {
    name: 'Mobile phone',
    keywords: 'smartphone cell phone old phone',
    category: 'ewaste',
    action: 'Treat as e-waste. Recycle through an authorised e-waste collector or create a sale listing.',
    canRecycle: true,
    canSell: true,
    pickup: true,
    safety: 'Back up and erase your personal data before handing it over.',
  },
  {
    name: 'Laptop',
    keywords: 'computer notebook pc',
    category: 'ewaste',
    action: 'Treat as e-waste. Do not dispose of it with normal household waste.',
    canRecycle: true,
    canSell: true,
    pickup: true,
    safety: 'Erase your data. Do not try to open or puncture the battery.',
  },
  {
    name: 'Charger / cables',
    keywords: 'charger cable wire adapter earphones',
    category: 'ewaste',
    action: 'Collect with other e-waste and give to an authorised e-waste collector.',
    canRecycle: true,
    canSell: true,
    pickup: true,
    safety: 'Do not burn cables to recover copper - the smoke is toxic.',
  },
  {
    name: 'Battery',
    keywords: 'aa aaa cell lithium battery power bank',
    category: 'hazardous',
    action: 'Use an appropriate specialised collection service or battery drop-off point.',
    canRecycle: true,
    canSell: false,
    pickup: true,
    safety: 'Never burn, crush or puncture batteries. Tape the terminals and store in a cool, dry place.',
  },
  {
    name: 'Paint container',
    keywords: 'paint can tin thinner varnish',
    category: 'hazardous',
    action: 'Keep the lid closed and use a specialised hazardous-waste collection service.',
    canRecycle: false,
    canSell: false,
    pickup: true,
    safety: 'Never pour paint or thinner into drains or soil.',
  },
  {
    name: 'Chemicals / cleaners',
    keywords: 'acid bleach pesticide chemical cleaner',
    category: 'hazardous',
    action: 'Keep in original labelled container and hand over to specialised hazardous-waste collection.',
    canRecycle: false,
    canSell: false,
    pickup: true,
    safety: 'Never mix chemicals. Keep away from children and pets.',
  },
  {
    name: 'Clothes',
    keywords: 'textile cloth garments shoes fabric',
    category: 'recyclable',
    action: 'Donate wearable clothes. Worn-out textiles can go to textile recyclers.',
    canRecycle: true,
    canSell: false,
    pickup: true,
    safety: 'Wash before donating.',
  },
  {
    name: 'Dirty tissues',
    keywords: 'tissue napkin used paper towel diaper',
    category: 'non_recyclable',
    action: 'Place in general (non-recyclable) waste.',
    canRecycle: false,
    canSell: false,
    pickup: true,
    safety: 'Wrap sanitary waste in paper before disposal.',
  },
  {
    name: 'Contaminated packaging',
    keywords: 'chip packet multilayer plastic food wrapper styrofoam',
    category: 'non_recyclable',
    action: 'Place in general waste. Avoid mixing with clean recyclables.',
    canRecycle: false,
    canSell: false,
    pickup: true,
    safety: 'Do not burn plastic packaging.',
  },
];
